### ISSUE TITLE
Fortigate connect via Paramiko fails as timeout argument is unexpected

### ISSUE THREAD

**Issue by bodleytunes** [z1pti3/jimiPlugin-remote#20]
As per below, the fix is to add the timeout=None to the command function:

```
    def command(self, command, args=[], elevate=False, runAs=None):
        self.channel.send("{0}{1}".format(command,"\n"))
        return (0, self.recv(), "")
```
to
```

    def command(self, command, args=[], elevate=False, runAs=None, timeout=None):
        self.channel.send("{0}{1}".format(command,"\n"))
        return (0, self.recv(), "")
```

![image](https://user-images.githubusercontent.com/619239/116720505-2c84e580-a9d4-11eb-93be-90c41a2d3ca9.png)

**Comment by z1pti3** [comment]
This bug is related to the remoteCommand action that passes in the timeout argument that is then not supported by the FortiGate class?

**Comment by bodleytunes** [comment]
Hi,
That's right yes.  It tries to pass the timeout=x to the fortigate.command() function and that function is not expecting the timeout argument so it fails.
Cheers!
Jon.

**Comment by z1pti3** [comment]
I have merged in the fix for this. Thanks
