### ISSUE TITLE
Feature - Ability to have clients pull down files hosted on JIMI via HTTP/S

### ISSUE THREAD

**Issue by TerrifiedBug** [z1pti3/jimiPlugin-remote#22]
I have a use case where I need to rapidly deploy/automate the installation of software for many users. The remote upload command is fine for uploading small software packages but at a large scale this will cause a bottleneck on upload bandwidth. 

Adding the ability to have JIMI tell the client to download the software package from JIMI itself over HTTP/S will make this more efficient and usable at a large scale.  The current workaround is to send a remote command to the client to do the following:

powershell -noprofile -executionpolicy bypass -command "Invoke-WebRequest -Uri 'http://server.net/Software/Setup.zip' -OutFile 'C:\Windows\Temp\Setup.zip'"

However, it makes more sense to be able to do this all within a plugin that tells the client to download from JIMI itself. This will help complete the functionality of using JIMI to push out the installation of software at scale. 

Thanks,
Danny

**Comment by z1pti3** [comment]
Hi,

Thank you for your feature request.

I felt this was more of a core feature than one for the remote plugin so have committed https://github.com/z1pti3/jimi/commit/c57fda3882fe912f6f5df4bbcc5d3402eb3145a1 to add this in beta.

Usage:
Once you have installed the latest version of jimi core

Model Editor -> Storage -> <StorageItem>

Add a new accessToken to accessTokens as a dictionary i.e.

![image](https://user-images.githubusercontent.com/66521110/118172174-f90a7800-b423-11eb-93ff-5b0e17d40bbc.png)

 [{"expiry":99999999999,"token":"9dac2991e0e8e7d1144f988b360be6f0f770b0fa1c29cb50235d9fbdab7e39c1"}]

The file is then accessible via http(|s)://<jimi_webURL>:<jimi_webPort>/api/1.0/storage/file/<Accesstoken>/

In the example above in my dev system it would be

http://127.0.0.1:5002/api/1.0/storage/file/9dac2991e0e8e7d1144f988b360be6f0f770b0fa1c29cb50235d9fbdab7e39c1/

In a future release we will look to add better UI functions to support this and maybe even dynamic sharing via a jimi action?


Any issues please let us know and once again thank you for using jimi
