### ISSUE TITLE
[Bug] - Linux timeout set in milliseconds but argument takes it in seconds

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimiPlugin-remote#23]
https://github.com/z1pti3/jimiPlugin-remote/blob/f0703476d5833c1dcfec0d6aed35cd7761288c2b/includes/linux.py#L48

Within the linux connector it is hard coded to 5000 seconds this should be changed to 10 seconds and/or made to be optional within the action that connects?

**Comment by b1scuit-thi3f** [comment]
Should be fixed in https://github.com/z1pti3/jimiPlugin-remote/commit/c54b3842296c4133dbfb5a06d67c21e29406d172
Timeout is set to 10s by default but can be modified by the user

**Comment by u-n-i-c-o-rn** [comment]
Great thank you
