### ISSUE TITLE
Debug able to be ran multiple times

### ISSUE THREAD

**Issue by TerrifiedBug** [z1pti3/jimiPlugin-remote#33]
I had experienced an issue whereby debugging a Test Fire Trigger resulted in it being triggered 4 times. 

Unknown why it ran 4 times as the number 4 does not reflect number of events, foreachs etc.

**Comment by z1pti3** [comment]
Unable to recreate within remote - however this commit to jimi may have fixed it

https://github.com/z1pti3/jimi/commit/ca3537d9def432b92bd313703b8c919ac0983d73
