### ISSUE TITLE
Bug - Download with storage does not complete ACL checking

### ISSUE THREAD

**Issue by z1pti3** [z1pti3/jimiPlugin-remote#43]
When using download with storage jimi simply checks that the storage file exists by name and does not check if the given action acl is allowed access

**Comment by b1scuit-thi3f** [comment]
48ffefa7a1e5a8364bbc6a00a7e06b3b68aacbc6 should hopefully fix this issue. It uses a new function I pushed to jimi that allows for the object to check that it's ACLs (which it inherits from the user that created it initially) give it enough permissions to read (when uploading) and write (downloading) to storage.
